### ISSUE TITLE
Handle NPE

### ISSUE THREAD

**Issue by zguesmi** [iExecBlockchainComputing/iexec-common#164]
```
2020-02-10 10:24:44.021  INFO 1 --- [pool-2-thread-8] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0xaca33026833319b46ba870a797c2e3cea5ba9dd76a9e64f55bf6f15cfaec0779, block:2153338]
2020-02-10 10:24:44.433  INFO 1 --- [pool-2-thread-8] com.iexec.core.task.TaskService          : Add new task [chainDealId:0xaca33026833319b46ba870a797c2e3cea5ba9dd76a9e64f55bf6f15cfaec0779, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:24:44.762  INFO 1 --- [ol-812-thread-1] com.iexec.core.chain.IexecHubService     : Requested  initialize [chainDealId:0xaca33026833319b46ba870a797c2e3cea5ba9dd76a9e64f55bf6f15cfaec0779, taskIndex:0, waitingTxCount:0]
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.iexec.core.chain.IexecHubService.initialize(IexecHubService.java:111)
	at com.iexec.core.task.TaskService.received2Initialized(TaskService.java:184)
	at com.iexec.core.task.TaskService.tryUpgradeTaskStatus(TaskService.java:114)
	at com.iexec.core.task.TaskExecutorEngine.lambda$updateTask$0(TaskExecutorEngine.java:37)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.iexec.core.chain.IexecHubService.sendInitializeTransaction(IexecHubService.java:146)
	at com.iexec.core.chain.IexecHubService.lambda$initialize$1(IexecHubService.java:111)
```

**Comment by zguesmi** [comment]
Not the correct repo.
